"""
This type stub file was generated by pyright.
"""

import logging
from .configuration import Configuration as Config
from .api import build, build_article, fulltext, hot, languages, popular_urls
from .article import Article, ArticleException
from .mthreading import NewsPool
from .source import Source
from .version import __version__

"""
Wherever smart people work, doors are unlocked. -- Steve Wozniak
"""
__title__ = ...
__author__ = ...
__license__ = ...
__copyright__ = ...
news_pool = ...
