"""
This type stub file was generated by pyright.
"""

from .article import Article
from .source import Source

"""
Ignore the unused imports, this file's purpose is to make visible
anything which a user might need to import from newspaper.
View newspaper/__init__.py for its usage.
"""
__title__ = ...
__author__ = ...
__license__ = ...
__copyright__ = ...
def build(url=..., dry=..., config=..., **kwargs) -> Source:
    """Returns a constructed source object without
    downloading or parsing the articles
    """
    ...

def build_article(url=..., config=..., **kwargs) -> Article:
    """Returns a constructed article object without downloading
    or parsing
    """
    ...

def languages(): # -> None:
    """Returns a list of the supported languages
    """
    ...

def popular_urls(): # -> list[str]:
    """Returns a list of pre-extracted popular source urls
    """
    ...

def hot(): # -> list[Unknown | list[FeedParserDict]] | None:
    """Returns a list of hit terms via google trends
    """
    ...

def fulltext(html, language=...): # -> str:
    """Takes article HTML string input and outputs the fulltext
    Input string is decoded via UnicodeDammit if needed
    """
    ...

