"""
This type stub file was generated by pyright.
"""

"""
Holds the code for cleaning out unwanted tags from the lxml
dom xpath.
"""
class DocumentCleaner:
    def __init__(self, config) -> None:
        """Set appropriate tag names and regexes of tags to remove
        from the HTML
        """
        ...
    
    def clean(self, doc_to_clean):
        """Remove chunks of the DOM as specified
        """
        ...
    
    def clean_body_classes(self, doc):
        """Removes the `class` attribute from the <body> tag because
        if there is a bad match, the entire DOM will be empty!
        """
        ...
    
    def clean_article_tags(self, doc):
        ...
    
    def clean_em_tags(self, doc):
        ...
    
    def remove_drop_caps(self, doc):
        ...
    
    def remove_scripts_styles(self, doc):
        ...
    
    def clean_bad_tags(self, doc):
        ...
    
    def remove_nodes_regex(self, doc, pattern):
        ...
    
    def clean_para_spans(self, doc):
        ...
    
    def get_flushed_buffer(self, replacement_text, doc):
        ...
    
    def replace_walk_left_right(self, kid, kid_text, replacement_text, nodes_to_remove): # -> None:
        ...
    
    def get_replacement_nodes(self, doc, div): # -> list[Unknown]:
        ...
    
    def replace_with_para(self, doc, div): # -> None:
        ...
    
    def div_to_para(self, doc, dom_type):
        ...
    


