"""
This type stub file was generated by pyright.
"""

from threading import Thread

"""
Anything that has to do with threading in this library
must be abstracted in this file. If we decide to do gevent
also, it will deserve its own gevent file.
"""
__title__ = ...
__author__ = ...
__license__ = ...
__copyright__ = ...
log = ...
class ConcurrencyException(Exception):
    ...


class Worker(Thread):
    """
    Thread executing tasks from a given tasks queue.
    """
    def __init__(self, tasks, timeout_seconds) -> None:
        ...
    
    def run(self): # -> None:
        ...
    


class ThreadPool:
    def __init__(self, num_threads, timeout_seconds) -> None:
        ...
    
    def add_task(self, func, *args, **kargs): # -> None:
        ...
    
    def wait_completion(self): # -> None:
        ...
    


class NewsPool:
    def __init__(self, config=...) -> None:
        """
        Abstraction of a threadpool. A newspool can accept any number of
        source OR article objects together in a list. It allocates one
        thread to every source and then joins.

        We allocate one thread per source to avoid rate limiting.
        5 sources = 5 threads, one per source.

        >>> import newspaper
        >>> from newspaper import news_pool

        >>> cnn_paper = newspaper.build('http://cnn.com')
        >>> tc_paper = newspaper.build('http://techcrunch.com')
        >>> espn_paper = newspaper.build('http://espn.com')

        >>> papers = [cnn_paper, tc_paper, espn_paper]
        >>> news_pool.set(papers)
        >>> news_pool.join()

        # All of your papers should have their articles html all populated now.
        >>> cnn_paper.articles[50].html
        u'<html>blahblah ... '
        """
        ...
    
    def join(self): # -> None:
        """
        Runs the mtheading and returns when all threads have joined
        resets the task.
        """
        ...
    
    def set(self, news_list, threads_per_source=..., override_threads=...): # -> None:
        """
        news_list can be a list of `Article`, `Source`, or both.

        If caller wants to decide how many threads to use, they can use
        `override_threads` which takes precedence over all. Otherwise,
        this api infers that if the input is all `Source` objects, to
        allocate one thread per `Source` to not spam the host.

        If both of the above conditions are not true, default to 1 thread.
        """
        ...
    


