"""
This type stub file was generated by pyright.
"""

"""
Output formatting to text via lxml xpath nodes abstracted in this file.
"""
__title__ = ...
__author__ = ...
__license__ = ...
__copyright__ = ...
log = ...
class OutputFormatter:
    def __init__(self, config) -> None:
        ...
    
    def update_language(self, meta_lang): # -> None:
        '''Required to be called before the extraction process in some
        cases because the stopwords_class has to set incase the lang
        is not latin based
        '''
        ...
    
    def get_top_node(self): # -> None:
        ...
    
    def get_formatted(self, top_node): # -> tuple[str, Unknown | Literal['']]:
        """Returns the body text of an article, and also the body article
        html if specified. Returns in (text, html) form
        """
        ...
    
    def convert_to_text(self): # -> str:
        ...
    
    def convert_to_html(self):
        ...
    
    def add_newline_to_br(self): # -> None:
        ...
    
    def add_newline_to_li(self): # -> None:
        ...
    
    def links_to_text(self): # -> None:
        """Cleans up and converts any nodes that should be considered
        text into text.
        """
        ...
    
    def remove_negativescores_nodes(self): # -> None:
        """If there are elements inside our top node that have a
        negative gravity score, let's give em the boot.
        """
        ...
    
    def replace_with_text(self): # -> None:
        """
        Replace common tags with just text so we don't have any crazy
        formatting issues so replace <br>, <i>, <strong>, etc....
        With whatever text is inside them.
        code : http://lxml.de/api/lxml.etree-module.html#strip_tags
        """
        ...
    
    def remove_empty_tags(self): # -> None:
        """It's common in top_node to exit tags that are filled with data
        within properties but not within the tags themselves, delete them
        """
        ...
    
    def remove_trailing_media_div(self): # -> None:
        """Punish the *last top level* node in the top_node if it's
        DOM depth is too deep. Many media non-content links are
        eliminated: "related", "loading gallery", etc
        """
        ...
    


